name: 'Build Test'
on: # rebuild any PRs and main branch changes
  pull_request:
    paths:
      - '.github/workflows/build-test.yml'
      - '__tests__/**'
      - 'dist/**'
      - 'src/**'
      - 'types/**'
      - '.eslint*'
      - '*ts'
      - '*.json'
      - 'serverless.yml'
  push:
    branches:
      - main
      - releases/*
    paths:
      - '.github/workflows/build-test.yml'
      - '__tests__/**'
      - 'dist/**'
      - 'src/**'
      - 'types/**'
      - '.eslint*'
      - '*ts'
      - '*.json'
      - 'serverless.yml'

env:
  TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
  TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}

jobs:
  build:
    name: 'Build Test'
    needs: [ 'tests' ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.16' ]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2.1.6
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - name: Build test
        run: yarn build


  eslint:
    name: 'Eslint'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.16' ]
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2.1.6
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - name: Check with eslint
        run: yarn lint

  tests:
    name: 'Tests'
    needs: [ 'eslint' ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.16' ]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2.1.6
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - name: Unit tests
        run: yarn test --coverage