name: 'Build Test'
on: # rebuild any PRs and main branch changes
  pull_request:
    paths:
      - '.github/workflows/build-test.yml'
      - '__tests__/**'
      - 'dist/**'
      - 'src/**'
      - 'types/**'
      - '.eslint*'
      - '*ts'
      - '*.json'
      - 'serverless.yml'
  push:
    branches:
      - main
      - releases/*
    paths:
      - '.github/workflows/build-test.yml'
      - '__tests__/**'
      - 'dist/**'
      - 'src/**'
      - 'types/**'
      - '.eslint*'
      - '*ts'
      - '*.json'
      - 'serverless.yml'

env:
  TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
  TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY}}

jobs:
  build: # make sure build/ci work properly
    name: 'Build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.16' ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: rm -f .yarnclean
      - run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - run: yarn
      - run: yarn build

  eslint:
    name: 'Eslint'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.16' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: rm -f .yarnclean
      - run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - run: yarn
      - run: yarn lint

  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.16' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: rm -f .yarnclean
      - run: yarn --frozen-lockfile
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - run: yarn
      - run: yarn test --coverage